Models/GroupChatViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace chatting.Models
{
    public class GroupChatViewModel
    {
        public group Group { get; set; }
        public List<groupmessage> Messages { get; set; }
        public string NewMessage { get; set; }
    }
}

Models/group.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chatting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public group()
        {
            this.usergroups = new HashSet<usergroups>();
            this.groupmessage = new HashSet<groupmessage>();
        }
    
        public int gid { get; set; }
        public int groupkatılım { get; set; }
        public string groupname { get; set; }
        public string groupdescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usergroups> usergroups { get; set; }
        public virtual groupmessage groupmessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<groupmessage> groupmessage1 { get; set; }
    }
}

Controllers/GroupController.cs
using Qu2SM.Models;
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Qu2SM.Controllers
{
    public class GroupController : Controller
    {
        private chattingonlyEntities db = new chattingonlyEntities();


        public ActionResult Index()
        {
            return View(); 
        }
        public ActionResult CreateGroup()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateGroup(group group)
        {
            if (ModelState.IsValid)
            {
                Random random = new Random();
                int newGroupCode = random.Next(1000, 1000000000); //grup katılım kodunu rastgele veriyorum.

                var newGroup = new group
                {
                    groupname = group.groupname,
                    groupkatılım = newGroupCode
                };
                db.group.Add(newGroup);
                db.SaveChanges();

                string userId = User.Identity.Name;
                var userGroup = new usergroups
                {
                    user_id = db.user.FirstOrDefault(u => u.useremail == userId).userid,
                    group_id = newGroup.gid
                };
                db.usergroups.Add(userGroup); //burada logları basitleştirmek için kullanıcı ve grubu usergroups modelinde tutuyorum.
                db.SaveChanges();

                return RedirectToAction("Index", "Home");
            }

            return View(group);
        }

        public ActionResult JoinGroup()
        {
            return View();
        }

        [HttpPost]
        public ActionResult JoinGroup(int? groupCode)
        {
            if (groupCode.HasValue)
            {
                var existingGroup = db.group.FirstOrDefault(g => g.groupkatılım == groupCode);

                if (existingGroup != null)
                {
                    string userId = User.Identity.Name;

                    var userGroup = new usergroups
                    {
                        user_id = db.user.FirstOrDefault(u => u.useremail == userId).userid,
                        group_id = existingGroup.gid
                    };
                    db.usergroups.Add(userGroup);
                    db.SaveChanges();

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("groupCode", "Geçersiz grup kodu.");
                }
            }
            else
            {
                ModelState.AddModelError("groupCode", "Grup katılım kodunu girin.");
            }

            return View();
        }

        public ActionResult MyGroups() //Bu kısımda Kullanıcı üyesi olduğu grupları görebiliyor.
        {
            string userId = User.Identity.Name;
            var user = db.user.FirstOrDefault(u => u.useremail == userId);

            if (user != null)
            {
                var userGroups = db.usergroups
                    .Where(ug => ug.user_id == user.userid)
                    .Select(ug => ug.group)
                    .ToList();

                return View(userGroups);
            }
            else
            {
                return RedirectToAction("NotFound", "Error");
            }
        }

        public ActionResult GroupChat()
        {
            return View();
        }
        [HttpGet]
        public ActionResult GroupChat(int groupId) //Bu kısım varolan grupta konuşma yapabileceği kısım.
        {
            bool isUserMemberOfGroup = CheckIfUserIsMemberOfGroup(User.Identity.Name, groupId);

            if (isUserMemberOfGroup)
            {
                var group = db.group.FirstOrDefault(g => g.gid == groupId);
                ViewBag.GroupName = group.groupname;
                ViewBag.Groupdescp = group.groupdescription;
                ViewBag.Groupdavet = group.groupkatılım;

                ViewBag.GroupId = groupId;

                var groupMessages = db.groupmessage // tarihe göre sıralama
                    .Where(m => m.group_id == groupId)
                    .OrderBy(m => m.date)
                    .ToList();

                var groupMembers = db.usergroups
                    .Where(ug => ug.group_id == groupId)
                    .Select(ug => ug.user)
                    .ToList();

                ViewBag.GroupMembers = groupMembers;

                return View(groupMessages);
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Bu gruba üye değilsiniz ve grup sohbetini görüntüleyemezsiniz."); // Kişi başkasından grup linkini alır katılmak isterse hata veriyor.
                return View();
            }
        }



        [HttpPost]
        public ActionResult SendMessage(int groupId, string messageText) //mesaj gönderme kısmı
        {
            bool isUserMemberOfGroup = CheckIfUserIsMemberOfGroup(User.Identity.Name, groupId);

            if (isUserMemberOfGroup)
            {
                var newMessage = new groupmessage
                {
                    gmessage = messageText,
                    date = DateTime.Now,
                    group_id = groupId,
                    user_id = db.user.FirstOrDefault(u => u.useremail == User.Identity.Name).userid //belirli özeliikleri referans alarak atılan mesajın idsini alıyor ve hangi grupta atıldıysa onun idsini alıyor.
                };

                db.groupmessage.Add(newMessage);
                db.SaveChanges();

                return RedirectToAction("GroupChat", new { groupId = groupId });
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Bu gruba üye değilsiniz ve mesaj gönderemezsiniz.");
                return View(); 
            }
        }
        private bool CheckIfUserIsMemberOfGroup(string userName, int groupId) //Bu kısımda üye o grupta mı değil mi onun kontrolü oluyor.
        {
            using (var db = new chattingonlyEntities())
            {
                var user = db.user.FirstOrDefault(u => u.useremail == userName);
                if (user != null)
                {
                    var userGroup = db.usergroups.FirstOrDefault(ug => ug.user_id == user.userid && ug.group_id == groupId);
                    return userGroup != null; 
                }
                return false; 
            }
        }
        public ActionResult LeaveGroup(int groupId)
        {
            string userId = User.Identity.Name;

            bool isUserMemberOfGroup = CheckIfUserIsMemberOfGroup(userId, groupId);

            if (isUserMemberOfGroup)
            {
                using (var db = new chattingonlyEntities())
                {
                    var user = db.user.FirstOrDefault(u => u.useremail == userId);
                    var userGroup = db.usergroups.FirstOrDefault(ug => ug.user_id == user.userid && ug.group_id == groupId);

                    if (userGroup != null)
                    {
                        db.usergroups.Remove(userGroup);
                        db.SaveChanges();

                        return RedirectToAction("MyGroups");
                    }
                }
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Bu gruptan zaten çıktınız veya üye değilsiniz.");
            }

            return RedirectToAction("GroupChat", new { groupId = groupId });
        }

        public ActionResult GroupMembers(int groupId)
        {
            var groupMembers = db.user
                .Where(u => u.usergroups.Any(ug => ug.group_id == groupId))
                .ToList();

            return View(groupMembers);
        }

 

    }

}

Views/Group/Create.cshtml
@model chatting.Models.group

@{
    ViewBag.Title = "Yeni Grup Oluştur veya Gruba Katıl";
}

<h2>Yeni Grup Oluştur veya Gruba Katıl</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Grup Bilgileri</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.groupname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.groupname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.groupname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" name="createGroup" value="Yeni Grup Oluştur" class="btn btn-default" />
                <input type="submit" name="joinGroup" value="Gruba Katıl" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Geri Dön", "Index")
</div>

Views/Group/CreateOrJoin.cshtml
@{
    ViewBag.Title = "Yeni Grup Oluştur veya Gruba Katıl";
}

<h2>Yeni Grup Oluştur veya Gruba Katıl</h2>

<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("CreateOrJoin", "Group", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <h4>Yeni Grup Oluştur</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <label for="groupname">Başlık</label>
                <input type="text" id="groupname" name="groupname" class="form-control" />
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" name="groupname" value="Yeni Grup Oluştur" class="btn btn-default" />
                </div>
            </div>
        }
    </div>
    <div class="col-md-6">
        @using (Html.BeginForm("CreateOrJoin", "Group", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <h4>Gruba Katıl</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <label for="groupCode">Grup Kodu</label>
                <input type="text" id="groupkatılım" name="groupkatılım" class="form-control" />
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" name="groupkatılım" value="Gruba Katıl" class="btn btn-default" />
                </div>
            </div>
        }
    </div>
</div>

<div>
    @Html.ActionLink("Geri Dön", "Index")
</div>

Views/Group/GroupChat.cshtml
@model List<Qu2SM.Models.groupmessage>

@{
    ViewBag.Title = "Grup Sohbeti - " + ViewBag.GroupName + " | Grup Davet Kodu -" + ViewBag.GroupCode;
}

<h2>Grup Sohbeti - @ViewBag.GroupName | Grup Davet Kodu @ViewBag.groupdavet</h2>
<h3>@ViewBag.Groupdescp</h3>

<div id="chat-container">
    <div id="chat-box">
        @foreach (var message in Model)
        {
            <div class="message">
                <span class="message-timestamp">@message.date</span>
                <span class="message-text">@message.gmessage</span>
                <span class="message-sender">-->@message.user.usernickname</span>
            </div>
        }
    </div>

    <form id="message-form" action="@Url.Action("SendMessage", "Group", new { groupId = ViewBag.GroupId })" method="post">
        <input type="text" id="messageText" name="messageText" class="form-control" required placeholder="Mesajınızı buraya yazın..." />
        <button type="submit" class="btn btn-primary">Gönder</button>
    </form>

    <p>
        <a href="@Url.Action("LeaveGroup", "Group", new { groupId = ViewBag.GroupId })">Grubu Terk Et</a>
    </p>

</div>

<div id="user-list">
    <h3>Grup Üyeleri</h3>
    @foreach (var usergroup in ViewBag.GroupMembers)
    {
        <p>@usergroup.usernickname</p>
    }
</div>

<style>
    #chat-container {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: flex-end;
        height: 80vh;
        overflow-y: scroll;
    }

    #chat-box {
        flex-grow: 1;
        width: 100%;
        max-height: 60vh;
        overflow-y: auto;
        margin-bottom: 10px;
    }

    #message-form {
        width: 100%;
        text-align: center;
    }
</style>

Views/Group/Index.cshtml
@{
    ViewBag.Title = "Gruplara Katıl veya Yeni Grup Oluştur";
}

<h2>Gruplara Katıl veya Yeni Grup Oluştur</h2>

<div class="row">
    <div class="col-md-6">
        <h3>Yeni Grup Oluştur</h3>
        @using (Html.BeginForm("CreateGroup", "Group", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div class="form-group">
                <label for="groupName">Grup Adı:</label>
                <input type="text" id="groupName" name="groupName" class="form-control" required />
            </div>
            <button type="submit" class="btn btn-primary">Yeni Grup Oluştur</button>
        }
    </div>
    <div class="col-md-6">
        <h3>Gruba Katıl</h3>
        @using (Html.BeginForm("JoinGroup", "Group", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div class="form-group">
                <label for="groupCode">Grup Kodu:</label>
                <input type="text" id="groupCode" name="groupCode" class="form-control" required />
            </div>
            <button type="submit" class="btn btn-success">Gruba Katıl</button>
        }
    </div>
</div>

Views/Group/MyGroups.cshtml
@model List<Qu2SM.Models.group>

@{
    ViewBag.Title = "Gruplarım";
}

<h2>Gruplarım</h2>

@if (Model != null && Model.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>Grup Adı</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var group in Model)
            {
                <tr>
                    <td>@group.groupname</td>
                    <td>
                        @Html.ActionLink("Gruba Git", "GroupChat", "Group", new { groupId = group.gid }, null)
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Gruplarınız bulunmamaktadır.</p>
}

<div>
    @Html.ActionLink("Geri Dön", "Index", "Home")
    @Html.ActionLink("Gruba katıl ya da oluştur", "Index")

</div>